Repository kubeflow/kubebench, pull requests merged in 2018-06, with the labels that each got.

#27 reporter added to workflow
  components/tf_cnn_benchmarks/log_reporter.Dockerfile
  components/tf_cnn_benchmarks/log_reporter.py
  examples/tf_cnn_benchmarks/test/test_workflow.yaml
  examples/tf_cnn_benchmarks/test/tf_cnn_config.yaml
Labels: approved, lgtm, size/L

#25 Add python and jsonnet tests to e2e workflow
  .pylintrc
  components/common/configurator/tf-job.libsonnet
  components/tf_cnn_benchmarks/csv_reporter.py
  components/tf_cnn_benchmarks/runner.py
  kubebench/kubebench-job/kubebench-job.libsonnet
  kubebench/kubebench-job/prototypes/kubebench-job.jsonnet
  test/workflows/components/workflows.jsonnet
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/base.libsonnet
  test/workflows/environments/test/main.jsonnet
  test/workflows/environments/test/params.libsonnet
  test/workflows/lib/v1.7.0/k.libsonnet
  test/workflows/lib/v1.7.0/k8s.libsonnet
Labels: approved, lgtm, size/XXL

#40 Fix log reporter
  components/tf_cnn_benchmarks/log_reporter.Dockerfile
  components/tf_cnn_benchmarks/log_reporter.py
Labels: approved, lgtm, size/S

#42 Add pvc setup config in tf-cnn example
  examples/tf_cnn_benchmarks/nfs_pvc.yaml
Labels: approved, lgtm, size/S

#43 Add initial version of getting started guide
  README.md
Labels: approved, lgtm, size/L
