Repository kubeflow/kubebench, pull requests merged in 2018-08, with the labels that each got.

#58 adding as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#59 adding a smoke test #46
  kubebench/nfs-server/nfs-server.libsonnet
  kubebench/nfs-server/parts.yaml
  kubebench/nfs-server/prototypes/nfs-server.jsonnet
  kubebench/nfs-volume/nfs-volume.libsonnet
  kubebench/nfs-volume/parts.yaml
  kubebench/nfs-volume/prototypes/nfs-volume.jsonnet
  kubebench/registry.yaml
  test/py/kubebench/test/deploy_kubeflow.py
  test/py/kubebench/test/deploy_utils.py
  test/py/kubebench/test/test_kubebench_job.py
Labels: approved, lgtm, size/L

#65 Fix argument order in configurator's tf-job.jsonnet
  README.md
  components/common/configurator/tf-job.jsonnet
  test/py/kubebench/test/test_kubebench_job.py
Labels: approved, lgtm, size/XS

#68 add swiftdiaries to approvers list
  OWNERS
Labels: approved, lgtm, size/XS

#67 Add refactored basic reporter
  controller/cmd/reporter/app/csv_reporter.go
  controller/cmd/reporter/app/reporter.go
  controller/cmd/reporter/main.go
Labels: approved, lgtm, size/L

#72 Adds gofmt check.
  .travis.yml
  Makefile
  README.md
  hack/verify-gofmt.sh
Labels: approved, lgtm, size/M

#75 Add dockerfile for controller
  build/images/controller/Dockerfile
  controller/misc/fake_kubeconfig
Labels: approved, lgtm, size/M

#77 Fix missing dependencies
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_linux.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: approved, lgtm, size/XXL
