Repository kubeflow/kubebench, pull requests merged in 2018-09, with the labels that each got.

#82 Set name for wait_for_deployment test suite in e2e tests
  test/py/kubebench/test/wait_for_deployment.py
Labels: approved, lgtm, size/XS

#89 OWNERS: Add gaocegege
  OWNERS
Labels: approved, lgtm, size/XS

#74 Add refactored argo workflow
  kubebench/kubebench-job/kubebench-job-legacy.libsonnet
  kubebench/kubebench-job/kubebench-job.libsonnet
  kubebench/kubebench-job/prototypes/kubebench-job-legacy.jsonnet
  kubebench/kubebench-job/prototypes/kubebench-job.jsonnet
  test/py/kubebench/test/test_kubebench_job.py
Labels: approved, lgtm, size/XL

#78 Add refactored tf-cnn example workload
  build/images/examples/tf-cnn/post_processor.Dockerfile
  build/images/examples/tf-cnn/runner_cpu.Dockerfile
  build/images/examples/tf-cnn/runner_gpu.Dockerfile
  examples/config/tf-cnn/tf-cnn-dummy.yaml
  examples/src/tf-cnn/post_processor.py
  examples/src/tf-cnn/runner.py
  kubebench/kubebench-examples/parts.yaml
  kubebench/kubebench-examples/prototypes/tf-cnn.jsonnet
  kubebench/registry.yaml
Labels: approved, lgtm, size/XL

#83 Controller functionality updates
  controller/cmd/configurator/app/configurator.go
  controller/cmd/configurator/app/file_operator.go
  controller/cmd/configurator/app/options.go
  controller/cmd/configurator/main.go
  controller/cmd/reporter/app/csv_reporter.go
Labels: approved, lgtm, size/L

#84 Fix and improve controller image
  build/images/controller/Dockerfile
Labels: approved, lgtm, size/XS

#92 Fix source path in dockerfiles
  build/images/examples/tf-cnn/post_processor.Dockerfile
  build/images/examples/tf-cnn/runner_cpu.Dockerfile
  build/images/examples/tf-cnn/runner_gpu.Dockerfile
Labels: approved, lgtm, size/XS

#100 Fix example tf-cnn job prototype for worker only job
  kubebench/kubebench-examples/prototypes/tf-cnn.jsonnet
Labels: approved, lgtm, size/XS

#98 Simplify experiment job configs and decouple prototype info
  controller/cmd/configurator/app/configurator.go
  controller/cmd/configurator/app/manifest_generator.go
  controller/cmd/configurator/app/options.go
  controller/cmd/configurator/app/types.go
  controller/pkg/apis/kubebench/v1alpha1/types.go
  examples/config/tf-cnn/tf-cnn-dummy.yaml
  kubebench/kubebench-job/kubebench-job.libsonnet
  kubebench/kubebench-job/prototypes/kubebench-job.jsonnet
Labels: approved, lgtm, size/L

#79 Add quickstart installer package
  kubebench/kubebench-quickstarter/kubebench-quickstarter-service.libsonnet
  kubebench/kubebench-quickstarter/kubebench-quickstarter-volume.libsonnet
  kubebench/kubebench-quickstarter/parts.yaml
  kubebench/kubebench-quickstarter/prototypes/kubebench-quickstarter-service.jsonnet
  kubebench/kubebench-quickstarter/prototypes/kubebench-quickstarter-volume.jsonnet
  kubebench/registry.yaml
Labels: approved, lgtm, size/L

#101 Update readme with the latest changes
  README.md
Labels: approved, lgtm, size/L

#105 Add quickstarter installation/uninstallation scripts
  README.md
  scripts/install_quickstarter.sh
  scripts/uninstall_quickstarter.sh
Labels: approved, lgtm, size/M

#103 Improve kubebench-job ksonnet package
  kubebench/kubebench-job/kubebench-job.libsonnet
  kubebench/kubebench-job/prototypes/kubebench-job.jsonnet
Labels: approved, lgtm, size/L

#104 Add RBAC support in ksonnet package of kubebench-job
  kubebench/kubebench-job/kubebench-job.libsonnet
  kubebench/kubebench-job/prototypes/kubebench-job.jsonnet
Labels: approved, lgtm, size/M

#108 Add build scripts for auto image releasing
  build/images/controller/Dockerfile
  build/images/controller/build_image.sh
  build/images/examples/build_image.sh
  build/images/examples/tf-cnn/build_image.sh
  build/images/examples/tf-cnn/post-processor.Dockerfile
  build/images/examples/tf-cnn/runner-cpu.Dockerfile
  build/images/examples/tf-cnn/runner-gpu.Dockerfile
Labels: approved, lgtm, size/L

#111 Improve quick starter file server
  kubebench/kubebench-quickstarter/kubebench-quickstarter-service.libsonnet
Labels: approved, lgtm, size/S

#107 Fix RBAC support in ksonnet package
  kubebench/kubebench-job/kubebench-rbac.libsonnet
Labels: approved, lgtm, size/L

#113 Add namespace to installation script
  scripts/install_quickstarter.sh
Labels: approved, lgtm, size/XS

#116 Fix experiment id generation
  controller/cmd/configurator/app/configurator.go
Labels: approved, lgtm, size/XS

#118 fix prow config for postsubmit
  prow_config.yaml
Labels: approved, lgtm, size/XS

#119 Add user guide
  README.md
  doc/images/kubebench_high_level.png
  doc/images/writing_kubebench_jobs.png
  doc/user_guide.md
Labels: approved, lgtm, size/L

#120 Disable CGO in go build
  build/images/controller/build_image.sh
Labels: approved, lgtm, size/XS
