Repository kubeflow/kubebench, pull requests merged in 2018-10, with the labels that each got.

#130 Fix namespace param in deploy_kubeflow script for testing
  test/py/kubebench/test/deploy_kubeflow.py
Labels: approved, lgtm, size/S

#129 set LD_LIBRARY_PATH correctly in gpu image
  build/images/examples/tf-cnn/runner-gpu.Dockerfile
Labels: approved, lgtm, size/XS

#121 Grafana Dashboard for Kubebench
  dashboard/grafana-dashboard/README.md
  dashboard/grafana-dashboard/images/kubebench_dashboard.png
  dashboard/grafana-dashboard/kubebench-dashboard.json
Labels: approved, lgtm, size/L

#128 Monitoring system for Kubebench
  doc/monitoring_system.md
  kubebench/kubebench-examples/prototypes/tf-cnn-with-monitoring.jsonnet
  kubebench/monitoring/grafana-dashboards/kubebench-monitoring.json
  kubebench/monitoring/monitoring-grafana.libsonnet
  kubebench/monitoring/monitoring-kube-state-metrics.libsonnet
  kubebench/monitoring/monitoring-node-exporter.libsonnet
  kubebench/monitoring/monitoring-prometheus.libsonnet
  kubebench/monitoring/parts.yaml
  kubebench/monitoring/prometheus.yml
  kubebench/monitoring/prototypes/monitoring-grafana.jsonnet
  kubebench/monitoring/prototypes/monitoring-kube-state-metrics.jsonnet
  kubebench/monitoring/prototypes/monitoring-node-exporter.jsonnet
  kubebench/monitoring/prototypes/monitoring-prometheus.jsonnet
  kubebench/registry.yaml
Labels: approved, lgtm, size/XXL
