Repository kubeflow/kubebench, pull requests merged in 2018-05, with the labels that each got.

#4 Add initial e2e setup
  prow_config.yaml
  test/py/kubebench/__init__.py
  test/py/kubebench/test/__init__.py
  test/workflows/.ksonnet/registries/incubator/40285d8a14f1ac5787e405e1023cf0c07f6aa28c.yaml
  test/workflows/app.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.jsonnet
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/base.libsonnet
  test/workflows/environments/test/main.jsonnet
  test/workflows/environments/test/params.libsonnet
  test/workflows/lib/v1.7.0/k.libsonnet
  test/workflows/lib/v1.7.0/k8s.libsonnet
  test/workflows/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/XXL

#7 Add ksonnet package with basic benchmark workflow
  kubebench/kubebench-job/kubebench-job.libsonnet
  kubebench/kubebench-job/parts.yaml
  kubebench/kubebench-job/prototypes/kubebench-job.jsonnet
  kubebench/registry.yaml
Labels: approved, lgtm, size/L

#8 Add basic images needed by kubebench workflow
  images/benchmark_harness/runner_cpu.Dockerfile
  images/common/configurator.Dockerfile
  images/common/configurator/manifest_generator.py
  images/common/configurator/requirements.txt
  images/common/configurator/tf-job.jsonnet
  images/common/configurator/tf-job.libsonnet
Labels: approved, lgtm, size/L

#9 Add initial POC example
  examples/poc_benchmark_harness/benchmark_config.yaml
  examples/poc_benchmark_harness/example_params.libsonnet
  examples/poc_benchmark_harness/job_config.yaml
  examples/poc_benchmark_harness/schema.txt
Labels: approved, lgtm, size/M

#23 Add design doc
  doc/images/kubebench_workflow.png
  doc/kubebench_design.md
Labels: approved, lgtm, size/M

#24 Rename "image" dir to "components"
  components/benchmark_harness/runner_cpu.Dockerfile
  components/common/configurator.Dockerfile
  components/common/configurator/manifest_generator.py
  components/common/configurator/requirements.txt
  components/common/configurator/tf-job.jsonnet
  components/common/configurator/tf-job.libsonnet
Labels: approved, lgtm, size/XS

#26 add tf_cnn benchmarks example
  components/tf_cnn_benchmarks/runner.py
  components/tf_cnn_benchmarks/runner_cpu.Dockerfile
  examples/tf_cnn_benchmarks/pv.yaml
  examples/tf_cnn_benchmarks/pvc.yaml
  examples/tf_cnn_benchmarks/test_workflow.yaml
  examples/tf_cnn_benchmarks/tf_cnn_config.yaml
Labels: approved, lgtm, size/L

#28 reporter class to parse logs and save them to csv file
  components/tf_cnn_benchmarks/csv_reporter.Dockerfile
  components/tf_cnn_benchmarks/csv_reporter.py
Labels: approved, lgtm, size/L

#29 Update workflow and fixings
  components/common/configurator/manifest_generator.py
  components/common/configurator/tf-job.jsonnet
  components/tf_cnn_benchmarks/csv_reporter.py
  components/tf_cnn_benchmarks/runner.py
  components/tf_cnn_benchmarks/runner_cpu.Dockerfile
  examples/tf_cnn_benchmarks/job_config.yaml
  examples/tf_cnn_benchmarks/test/pv.yaml
  examples/tf_cnn_benchmarks/test/pvc.yaml
  examples/tf_cnn_benchmarks/test/test_workflow.yaml
  examples/tf_cnn_benchmarks/test/tf_cnn_config.yaml
  kubebench/kubebench-job/kubebench-job.libsonnet
  kubebench/kubebench-job/prototypes/kubebench-job.jsonnet
Labels: approved, lgtm, size/L
