Repository kubeflow/kubebench, pull requests merged in 2018-07, with the labels that each got.

#47 README: Add design doc
  README.md
Labels: approved, lgtm, size/S

#49 OWNERS: Add gaocegege
  OWNERS
Labels: approved, lgtm, size/XS

#55 adds swiftdiaries as reviewer
  OWNERS
Labels: lgtm, size/XS

#57 Fix readme
  README.md
Labels: approved, lgtm, size/S
