Repository kubeflow/kubebench, pull requests merged in 2019-02, with the labels that each got.

#165 Cleanup legacy ksonnet packages
  README.md
  kubebench/registry.yaml
Labels: approved, lgtm, ok-to-test, size/S

#167 Support MPI Job in kubebench
  Gopkg.lock
  Gopkg.toml
  build/images/examples/mpi/post-processor.Dockerfile
  controller/cmd/configurator/app/manifest_modifier.go
  controller/cmd/configurator/app/mpijob_manifest_modifier.go
  examples/config/mpi/mpi-job-dummy.yaml
  examples/src/mpi/post_processor.py
  vendor/github.com/kubeflow/mpi-operator/.dockerignore
  vendor/github.com/kubeflow/mpi-operator/LICENSE
  vendor/github.com/kubeflow/mpi-operator/pkg/apis/kubeflow/v1alpha1/doc.go
  vendor/github.com/kubeflow/mpi-operator/pkg/apis/kubeflow/v1alpha1/register.go
  vendor/github.com/kubeflow/mpi-operator/pkg/apis/kubeflow/v1alpha1/types.go
  vendor/github.com/kubeflow/mpi-operator/pkg/apis/kubeflow/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, ok-to-test, size/XL

#169 Update e2e test to sync with upstream kubeflow changes
  test/py/kubebench/test/deploy_kubeflow.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XS

#168 Add documentation for MPI benchmark job
  README.md
  examples/src/mpi/README.md
Labels: approved, lgtm, ok-to-test, size/L
