Repository kubeflow/kubebench, pull requests merged in 2019-07, with the labels that each got.

#205 Add MPIJob to configurator
  controller/examples/mpi-job.yaml
  controller/pkg/resource/condition/condition.go
  controller/pkg/resource/condition/job.go
  controller/pkg/resource/mod/modifier.go
  controller/pkg/resource/mod/mpijob.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#208 Fix test workflow
  test/py/kubebench/test/deploy_kubeflow.py
  test/py/kubebench/test/deploy_utils.py
  test/workflows/app.yaml
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#206 Add arguments, inputs and outputs for tasks
  controller/pkg/apis/kubebenchjob/v1alpha2/types.go
  controller/pkg/apis/kubebenchjob/v1alpha2/zz_generated.deepcopy.go
  controller/pkg/workflow/helper.go
  controller/pkg/workflow/workflow.go
Labels: approved, lgtm, size/L

#207 Fix kubebench-config passing in operator
  controller/pkg/controller/kubebenchjob/v1alpha2/controller.go
Labels: approved, lgtm, size/XS
