Repository kubeflow/kubebench, pull requests merged in 2019-04, with the labels that each got.

#178 Update dependencies for v1alpha2 API changes
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/golang/groupcache/LICENSE
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/k8s.io/client-go/tools/record/doc.go
  vendor/k8s.io/client-go/tools/record/event.go
  vendor/k8s.io/client-go/tools/record/events_cache.go
  vendor/k8s.io/client-go/tools/record/fake.go
Labels: approved, lgtm, size/XXL

#183 Add input-data and num-copies options to resource-manager
  controller/cmd/resource-manager/app/options.go
  controller/cmd/resource-manager/app/resource_manager.go
  controller/cmd/resource-manager/main.go
  controller/pkg/resource/client/resource_client.go
Labels: approved, lgtm, size/M

#184 Add build scripts for workflow agent
  build/images/workflow-agent/Dockerfile
  build/images/workflow-agent/build_image.sh
Labels: approved, lgtm, size/M

#185 Add workflow builder package for v1alpha2 api
  controller/pkg/workflow/helper.go
  controller/pkg/workflow/workflow.go
  controller/pkg/workflow/workflowinfo.go
Labels: approved, lgtm, size/XL

#186 Add CLI tool for workflow builder
  controller/cmd/cli/kubebench-workflow-builder/app/defaultconfig.go
  controller/cmd/cli/kubebench-workflow-builder/app/options.go
  controller/cmd/cli/kubebench-workflow-builder/app/workflowbuilder.go
  controller/cmd/cli/kubebench-workflow-builder/main.go
Labels: approved, lgtm, size/L

#187 update the runner image to public image
  examples/config/tf-cnn/tf-cnn-dummy.yaml
  kubebench/kubebench-examples/prototypes/tf-cnn.jsonnet
Labels: approved, lgtm, size/XS
